# Explicación estructuras de datos en ciencia de datos

**Autor:** Jazna Meza Hidalgo

**Correo Electrónico:** ja.meza@profesor.duoc.cl

**Fecha de Creación:** Marzo de 2026  
**Versión:** 1.0  

---

## Descripción

Este notebook ofrece un ejemplo de las principales estructuras de datos usadas en ciencia de datos.

Sienta las bases para comprender todo lo que viene.



---

## Requisitos de Software

Este notebook fue desarrollado con Python 3.12. A continuación se listan las bibliotecas necesarias:

- pandas (>=1.1.0)
- numpy (1.26.4)

Para verificar la versión instalada ejecutar usando el siguiente comando, usando la librería de la cual quieres saber la versión:

```python
import pandas as pd
print(pd.__version__)
````

In [ ]:
import pandas as pd
import numpy as np

#Lista

In [ ]:
notas = [5.5, 6.0, 4.8, 5.9, 6.3]

print(notas)
print(f"Primera nota : {notas[0]}")
print(f"Promedio: {sum(notas)/len(notas)}")

[5.5, 6.0, 4.8, 5.9, 6.3]
Primera nota : 5.5
Promedio: 5.7

+ Los datos están ordenados
+ Se accede por posición
+ Todos los valores representan el mismo tipo de información

**Problema que aparece**

*¿Qué pasa si ahora queremos guardar nombre del estudiante y notas?*

# Diccionario

In [ ]:
estudiante = {
    "nombre": "Ana",
    "edad": 20,
    "carrera": "Ingeniería",
    "nota_final": 5.8
}

print(estudiante["nombre"])
print(estudiante["nota_final"])

Ana
5.8

+ Cada dato tiene significado
+ No depende de la posición

**Problema que aparece**

*¿Y si hay muchos estudiantes?*

# Lista de diccionarios

In [ ]:
estudiantes = [
    {"nombre": "Ana", "edad": 20, "nota": 5.8},
    {"nombre": "Luis", "edad": 22, "nota": 6.1},
    {"nombre": "María", "edad": 21, "nota": 5.4},
    {"nombre": "Pedro", "edad": 23, "nota": 4.9}
]

print(estudiantes[0])
print(estudiantes[2]["nombre"])

{'nombre': 'Ana', 'edad': 20, 'nota': 5.8}
María

**Problema que aparece**

Un problema típico en ciencia de datos:

+ Calcular promedios
+ Filtrar
+ Analizar columnas

Esto se vuelve incómodo.

# Array de `numpy`

In [ ]:
notas = np.array([5.8, 6.1, 5.4, 4.9])

print(notas)
print(f"Promedio: {np.mean(notas)}")
print(f"Nota máxima: {np.max(notas)}")

[5.8 6.1 5.4 4.9]
Promedio: 5.549999999999999
Nota máxima: 6.1

+ Operaciones matemáticas muy rápidas
+ Optimizado para datos numéricos

In [ ]:
# Es posible hacer operaciones con vectores
notas_curva = notas + 0.2
print(notas_curva)

[6.  6.3 5.6 5.1]

**Problema que aparece**

*Y si se quiere guardar nombre, edad, carrera, nota. ¿Dónde se hace?*

# Dataframe

In [ ]:
datos = {
    "nombre": ["Ana", "Luis", "María", "Pedro"],
    "edad": [20, 22, 21, 23],
    "nota": [5.8, 6.1, 5.4, 4.9]
}

data = pd.DataFrame(datos)

data

  nombre  edad  nota
0    Ana    20   5.8
1   Luis    22   6.1
2  María    21   5.4
3  Pedro    23   4.9

## Operaciones típicas

### Promedio

In [ ]:
data["nota"].mean()

np.float64(5.549999999999999)

### Filtro de estudiantes aprobados

In [ ]:
data[data["nota"] >= 4.0]

  nombre  edad  nota
0    Ana    20   5.8
1   Luis    22   6.1
2  María    21   5.4
3  Pedro    23   4.9

### Agregar nuevas columnas

In [ ]:
data["aprobado"] = data["nota"] >= 4.0

### Algo un poco más elaborado ...

In [ ]:
data.loc[data["nota"].idxmax()]

nombre      Luis
edad          22
nota         6.1
aprobado    True
Name: 1, dtype: object

# Ejercicio

Contexto

Una plataforma quiere recomendar películas a sus usuarios según el género que prefieren.

In [ ]:
peliculas = [
    {"titulo": "Inception", "genero": "ciencia ficcion", "rating": 8.8},
    {"titulo": "Titanic", "genero": "romance", "rating": 7.9},
    {"titulo": "The Dark Knight", "genero": "accion", "rating": 9.0},
    {"titulo": "Interstellar", "genero": "ciencia ficcion", "rating": 8.6},
    {"titulo": "La La Land", "genero": "musical", "rating": 8.0},
    {"titulo": "Mad Max", "genero": "accion", "rating": 8.1}
]

In [ ]:
# Pregunta la preferencia del usuario
genero_preferido = input("¿Qué género de películas te gusta? ")

¿Qué género de películas te gusta? accion

## Buscar las recomendaciones

In [ ]:
for p in peliculas:
    if p["genero"] == genero_preferido:
        print(f"Te recomendamos: {p['titulo']}")

Te recomendamos: The Dark Knight
Te recomendamos: Mad Max

## Filtro por ranking

In [ ]:
for p in peliculas:
  if p["genero"] == genero_preferido and p["rating"] > 8:
    print(f"Te recomendamos: {p['titulo']}, | rating:  {p['rating']}")

Te recomendamos: The Dark Knight, | rating:  9.0
Te recomendamos: Mad Max, | rating:  8.1

## Crear una lista de recomendaciones

In [ ]:
recomendadas = []

for p in peliculas:
    if p["genero"] == genero_preferido and p["rating"] > 8:
        recomendadas.append(p["titulo"])

print("Películas recomendadas:", recomendadas)

Películas recomendadas: ['The Dark Knight', 'Mad Max']

## Ahora usted ...

+ Mostrar solo la película con mejor rating

+ Contar cuántas películas hay por género

+ Recomendar películas solo si rating > 8.5

+ Mostrar todas las películas ordenadas por rating

In [ ]:
# Escriba su código acá

....